---
- name: 'Install the Uyuni server'
  hosts: 'uyuniserver01'
  gather_facts: true
  become: true

  roles:
    - role: 'stdevel.uyuni.storage'
      uyuni_pv: '/dev/vdb'
    - role: 'stdevel.uyuni.server'
      uyuni_cert_city: 'Rockolding'
      uyuni_cert_country: 'DE'
      uyuni_cert_mail: 'root@localhost'
      uyuni_cert_o: 'vagrant-libvirt'
      uyuni_cert_ou: 'B1 Systems Training'
      uyuni_cert_state: 'Bavaria'
      uyuni_cert_pass: 'uyuni'
      uyuni_org_name: 'vagrant-libvirt-demo'
      uyuni_org_login: 'admin'
      uyuni_org_password: 'admin'
      uyuni_org_mail: 'root@localhost'
      uyuni_org_first_name: 'Tux'
      uyuni_org_last_name: 'Penguin'
